-- חלק ב: לקוחות
INSERT INTO clients (organization_id, name, source) SELECT id, 'אשכר טליה', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'סלק העברה ללא תמורה', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'סלומני העברה ללא תמורה', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'בירס -סולימני', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'סולימני - אחות בירס', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'רונן מני', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'משה זגזג', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'שחר סוזי וריקרדו-', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'אדלר דבורה', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'חזן - אינגה', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'ארבל אורן', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'הירש גבריאל וקטיה -', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'רונית שחר -', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'סגלי אמי אליזבטה - קורן', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'בן אברהם אליה', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'איתן שוחט', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'קונובלנקו פבל- פארס סימון', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'נורדמן - יוסי אלפסי', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'זר אביעד ונורית -', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'אלפסי יוסף -', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'צ''ורני יורי - מרגריטה', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'אונגר- גורלובסקי', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'קונדרטייב - איוונוב', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'רוגל יורם', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'גולוב- רחלי', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'וימר נורית- גירוושין', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'ויצמן - בוטורשוילי', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'בלסון קלאודין - ליאורה', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'נתנזון יובל- שקולניק ניקיטה', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'בנקליפה - גמר אייה', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'דהן אמנון ואח''', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'קרסנטי - אולג', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'גנס לב- בליומין', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'נאה יהודה ולירון- דיין', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'ביצ''קוב איגור - זנאתי', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'גורן - כץ', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'שלו - צ''ורני יורי', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'פישה - נסטרנקו זויה', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'רוזנטל - ויסוצקי', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'מרגריטה - קונדרטייב נינה', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'מואיסיס - וטפא', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'לוטם וליחי שושן', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'גורלובסקי אירינה - צ''רנין ילנה', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'לוסטיג - לוסטיג', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'רות פיילר - ניר דמרי', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'קשפר ויקטור - שגב', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'בולוס - גרזוזי', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'קאי מיכאל ומרגלית - עמר חלחיל', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'אבישי ואורטל עטיה  -', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'פרנקל - מזרחי ניקול', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'דותן פדידה - מקסים שבץ', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'לוי - גנס', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'רפאלי - סגל צבי', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'סגל - בורקוב', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'ניר מירקין -אמאל', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'גיא - חרסונסקי', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'שחר דינה', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'היטנר - פסח', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'עבדה - אריאלי נריה', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'לילך דהן - יוסיפוב', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'אופטובסקי', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'קרן, כרמלה, ניר- עוז אלדד וירדן', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'מויסה  - בן טוב איתי', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'ברזון - דהן עדי', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'גנס לב -יוחימנקו', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'אוחנה רותם ויפית - בובליל', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'אביטל ניסים - נעמה איברהים', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'קרני - דרנג אסא ואיריס', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'סער- סופר ממי ואלי חיים', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'חנינה ברמי ואח'' - שחר רונית וליאור', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'גאורי יוסף אדם', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'הררי -קופפרמן', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'רייף - אודי אוהד קליפי', 'excel_import' FROM organizations LIMIT 1;
INSERT INTO clients (organization_id, name, source) SELECT id, 'חזן - ספרינקלים', 'excel_import' FROM organizations LIMIT 1;