name: Deploy to Vercel

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        run: npx vercel deploy --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: team_SCBCmeCqW2pxMKmZMHLcoIpZ
          VERCEL_PROJECT_ID: prj_7RUwLJpNKBmMIfqVdk3y84VMgkWb
